#!/bin/sh

THIS_SCRIPT=$(readlink -f ${BASH_ARGV0:=$0})
THIS_DIR=${THIS_SCRIPT%/*}

# ----------------------------------------------

#set -x

HOSTNAME=$(hostname)
HOMEDIRREPO=${THIS_DIR}/home

mklnk ()
{
    local tgt=$1
    local lnk=$2

    if [ -L ${lnk} ]; then
        rm ${lnk}
    else
        rm -rf ${lnk}
    fi

    mkdir -p $(dirname ${lnk})

    ln -s ${tgt} ${lnk}
}

install_vim()
{
    mklnk ${HOMEDIRREPO}/_vim ${HOME}/.vim
}

doit ()
{
    install_vim

    mklnk ${HOMEDIRREPO}/_gitconfig ${HOME}/.gitconfig

    local vscode=${HOME}/.config/Code/User
    mkdir -p ${vscode}
    mklnk ${HOMEDIRREPO}/_config/Code/User/settings.json ${vscode}/settings.json 
    mklnk ${HOMEDIRREPO}/_config/Code/User/keybindings.json ${vscode}/keybindings.json 

    if [ ${HOSTNAME} = "prune2" ]; then
        mklnk ${HOMEDIRREPO}/_Xmodmap--msi ${HOME}/.Xmodmap
        mklnk ${HOMEDIRREPO}/openbox-rc--s130.xml ${HOME}/.config/openbox/lxqt-rc.xml
    elif [ ${HOSTNAME} = "prune3" ]; then
        mklnk ${HOMEDIRREPO}/_Xmodmap--s130 ${HOME}/.Xmodmap
        mklnk ${HOMEDIRREPO}/openbox-rc--s130.xml ${HOME}/.config/openbox/rc.xml
    else
        mklnk ${HOMEDIRREPO}/_Xmodmap ${HOME}/.Xmodmap
        mklnk ${HOMEDIRREPO}/openbox-rc.xml ${HOME}/.config/openbox/lubuntu-rc.xml
    fi
}

##

doit
