#!/bin/sh

THIS_SCRIPT=$(readlink -f ${BASH_ARGV0:=$0})
THIS_DIR=${THIS_SCRIPT%/*}

# ----------------------------------------------

#set -x

HOSTNAME=$(hostname)
HOMEDIRREPO=${THIS_DIR}/home

mklnk ()
{
    local tgt=$1
    local lnk=$2

    if [ -L ${lnk} ]; then
        rm ${lnk}
    else
        rm -rf ${lnk}
    fi

    mkdir -p $(dirname ${lnk})

    ln -s ${tgt} ${lnk}
}

sudo_cp_ifnecess ()
{
    local src="$1"
    local dst="$2"
    local doit=0

    if [ ! -e "${dst}" ]; then
        doit=1
    else
        cmp -s "${src}" "${dst}"
        if [ $? -ne 0 ]; then
            doit=1
        fi
    fi

    if [ ${doit} -eq 1 ]; then
        sudo cp "${src}" "${dst}"
    fi
}

install_touchpad ()
{
    sudo_cp_ifnecess root/etc/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/40-libinput.conf
}

install_vim()
{
    mklnk ${HOMEDIRREPO}/_vim ${HOME}/.vim
}

doit ()
{
    install_vim

    mklnk ${HOMEDIRREPO}/_gitconfig ${HOME}/.gitconfig

    local vscode=${HOME}/.config/Code/User
    mkdir -p ${vscode}
    mklnk ${HOMEDIRREPO}/_config/Code/User/settings.json ${vscode}/settings.json 
    mklnk ${HOMEDIRREPO}/_config/Code/User/keybindings.json ${vscode}/keybindings.json 

    if [ ${HOSTNAME} = "prune2" ]; then
        mklnk ${HOMEDIRREPO}/_Xmodmap--msi ${HOME}/.Xmodmap
        mklnk ${HOMEDIRREPO}/openbox-rc--s130.xml ${HOME}/.config/openbox/lxqt-rc.xml
        install_touchpad
    elif [ ${HOSTNAME} = "prune3" ]; then
        mklnk ${HOMEDIRREPO}/_Xmodmap--s130 ${HOME}/.Xmodmap
        mklnk ${HOMEDIRREPO}/openbox-rc--s130.xml ${HOME}/.config/openbox/lxqt-rc.xml
        install_touchpad
    else
        mklnk ${HOMEDIRREPO}/_Xmodmap ${HOME}/.Xmodmap
        mklnk ${HOMEDIRREPO}/openbox-rc.xml ${HOME}/.config/openbox/lubuntu-rc.xml
    fi
}

##

doit
