hi Visual      guifg=#FFFFFF guibg=#0000FF gui=none
hi DiffDelete  guifg=#000000 guibg=#E6E6FA gui=none


if &diff
	" Show horizontal scrollbar
    set guioptions+=b

    function <SID>DiffAlgoHisto()
        let g:diffopt_algo = 'algorithm:histogram'
        let &diffopt=g:diffopt_base . ',' . g:diffopt_algo . ',' . g:diffopt_inden
    endfunction

    function <SID>DiffAlgoPatience()
        let g:diffopt_algo = 'algorithm:patience'
        let &diffopt=g:diffopt_base . ',' . g:diffopt_algo . ',' . g:diffopt_inden
    endfunction

    function <SID>DiffAlgoMyers()
        let g:diffopt_algo = 'algorithm:myers'
        let &diffopt=g:diffopt_base . ',' . g:diffopt_algo . ',' . g:diffopt_inden
    endfunction

    function <SID>DiffAlgoMin()
        let g:diffopt_algo = 'algorithm:minimal'
        let &diffopt=g:diffopt_base . ',' . g:diffopt_algo . ',' . g:diffopt_inden
    endfunction

    function <SID>IwhiteToggle()
       if &diffopt =~ 'iwhite'
           set diffopt-=iwhite
       else
           set diffopt+=iwhite
       endif
    endfunction


    aunmenu ToolBar

    an 1.20 ToolBar.Refresh   :diffu<CR>
    tmenu ToolBar.Refresh     Refresh view

    an 1.30 ToolBar.SaveAll   :browse confirm wa<CR>
    tmenu ToolBar.SaveAll     Save all files

    an 1.35 ToolBar.-sep1-    <Nop>

    amenu 1.36 ToolBar.ToggleLineNum   :set number!<CR>
    tmenu ToolBar.ToggleLineNum Toggle line numbers

    an 1.40 ToolBar.-sep2-    <Nop>

    amenu 1.42 ToolBar.HSplit   <C-w>J
    tmenu ToolBar.HSplit Horzontal layout

    amenu 1.43 ToolBar.VSplit   <C-w>L
    tmenu ToolBar.VSplit Vertical layout

    an 1.44 ToolBar.-sep3-    <Nop>

    if !has("gui_athena")
        an 1.95   ToolBar.-sep4-        <Nop>
        an 1.100  ToolBar.Replace       :promptrepl<CR>
        vunmenu   ToolBar.Replace
        vnoremenu ToolBar.Replace       y:promptrepl <C-R>=<SID>FixFText()<CR><CR>
        an 1.110  ToolBar.FindNext      n
        an 1.120  ToolBar.FindPrev      N
    endif

    an 1.215 ToolBar.-sep5-       <Nop>

    amenu 1.250 ToolBar.DiffAlgo_Histo :call <SID>DiffAlgoHisto()<CR>
    tmenu ToolBar.DiffAlgo_Histo Histogram diff algorithm

    amenu 1.252 ToolBar.DiffAlgo_Patience :call <SID>DiffAlgoPatience()<CR>
    tmenu ToolBar.DiffAlgo_Patience Patience diff algorithm

    amenu 1.253 ToolBar.DiffAlgo_Myers :call <SID>DiffAlgoMyers()<CR>
    tmenu ToolBar.DiffAlgo_Myers Myers diff algorithm

    amenu 1.254 ToolBar.DiffAlgo_Min :call <SID>DiffAlgoMin()<CR>
    tmenu ToolBar.DiffAlgo_Min Minimal diff algorithm

    amenu 1.256 ToolBar.IwhiteToggle :call <SID>IwhiteToggle()<CR>
    tmenu ToolBar.IwhiteToggle Toggle whitespace ignore

    an 1.259 ToolBar.-sep6-       <Nop>

    amenu 1.260 ToolBar.NextDiff ]c
    tmenu ToolBar.NextDiff Next diff

    amenu 1.260 ToolBar.PrevDiff [c
    tmenu ToolBar.PrevDiff Prev diff

endif
