if &diff
    " Put the source evim first as we don't want it to override any
    " setting changes that we make
    source $VIMRUNTIME/evim.vim

    set lines=35
    set columns=130
    set noro
    syntax off
    set noshowmode
    set number

    let g:diffopt_base = 'internal,filler,context:1000000'
    let g:diffopt_algo = 'algorithm:histogram'
    let g:diffopt_inden = 'indent-heuristic'
    let g:diffopt_ws   = 'internal'

    let &diffopt=g:diffopt_base . ',' . g:diffopt_algo . ',' . g:diffopt_inden

    autocmd VimResized * exec "normal \<C-w>="

	" Map F3 to search (& replace)
    imap <F3> <C-o>:promptrepl<CR>

	" Map Save/Save all
    imap <C-s> <C-o>:browse confirm w<CR>
    imap <C-S-s> <C-o>:browse confirm wa<CR>
endif


set nocompatible
set expandtab
set shiftwidth=4
set tabstop=4
set nobackup nowritebackup

set fillchars=fold:-,diff:/

hi DiffAdd      gui=none    guifg=NONE          guibg=#e8ffd1
hi DiffChange   gui=none    guifg=NONE          guibg=#ADD8E6
hi DiffDelete   gui=bold    guifg=#000000       guibg=#E6E6FA
hi DiffText     gui=none    guifg=#D20000       guibg=#FFD2C8

